#!/usr/bin/env bash
## initial install script that just sets up the user.  Should be run from the user that will be used
## wget -qO- https://raw.github.com/steveash/devops/master/scriptname.sh | sh

echo copying public keys...
wget -q https://raw.github.com/steveash/devops/master/ashdev_rsa.pub
wget -q https://raw.github.com/steveash/devops/master/stevelaptop_rsa.pub

if [ ! -f ~/.ssh/authorized_keys ]; then
    mkdir -p ~/.ssh
    cat ashdev_rsa.pub >> ~/.ssh/authorized_keys
    cat stevelaptop_rsa.pub >> ~/.ssh/authorized_keys
    chmod 600 ~/.ssh/authorized_keys
    chmod 700 ~/.ssh
fi

TMUX_CFG = "~/.tmux.conf"
if [ ! -f $TMUX_CFG ]; then
    echo 'set-option -g prefix C-a' >> $TMUX_CFG
    echo 'bind-key C-a last-window' >> $TMUX_CFG
    echo 'set -g base-index 1' >> $TMUX_CFG
fi

##### zsh and shell config stuff
echo clone ohmyzsh
sudo curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
command -v zsh | sudo tee -a /etc/shells
sudo chsh -s `which zsh`

ZSH_CFG = "~/.zshrc"
wget -q https://raw.github.com/steveash/devops/master/zshrc_limited

if [ ! -f "${ZSH_CFG}.original" ]; then
    cp $ZSH_CFG "${ZSH_CFG}.original"
fi
mv zshrc_limited $ZSH_CFG

echo '******** all done **********'

